version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: fl-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: fl-server
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_TOKEN=${API_TOKEN:-demo-token-123}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://localhost:8000}
      - STORAGE_PATH=/app/storage
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./intake:/app/intake
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  intake-watcher:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: fl-intake-watcher
    command: python -m server.intake_watcher
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INTAKE_PATH=/app/intake
      - STORAGE_PATH=/app/storage
    volumes:
      - ./intake:/app/intake
      - ./storage:/app/storage
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped

  fl-aggregator:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: fl-aggregator
    command: python -m server.fl_controller
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STORAGE_PATH=/app/storage
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  default:
    name: fl-network
    driver: bridge